### ISSUE TITLE
Behavior of elasticsearch-analysis-kuromoji is not what i expected

### ISSUE THREAD

**Issue by GMelo** [elastic/elasticsearch-analysis-kuromoji#57]
Hello, Am not sure this is a issue, I looking though old issues and wrote on stackoverflow and have not seem anything like this...

I have been using elasticsearch-analysis-kuromoji 2.3.0 with elasticsearch 1.35 to perform searches in Japanese, but I have been getting two very strange behaviours, the first one being that the characters I search for will not work, like - '輸出貿易' will not work unless I pass it as '輸 出 貿 易' with spaces between each character. Also characters like ント are not searched on.

This is my configuration:

            .setSettings(ImmutableSettings.settingsBuilder().loadFromSource(jsonBuilder()
                    .startObject()
                    .startObject("analysis")
                            //
                    .startObject("tokenizer")
                    .startObject("kuromoji_user_dict")
                    .field("type", "kuromoji_tokenizer")
                    .field("mode", "extended")
                    .field("discard_punctuation", "false")
                    .endObject()
                    .endObject()
                            //
                    .startObject("analyzer")
                    .startObject(JAPANESE_LANGUAGE_ANALYSIS)
                    .field("type", "custom")
                    .field("tokenizer", "kuromoji_user_dict")
                    .endObject()
                    .endObject()
                            //

                    .endObject()
                    .endObject().string()));

Am I configuring it wrong or do I need a different tokeniser for character like: '輸出貿易 and ント'

Thank You

**Comment by dadoonet** [comment]
@johtani assigning this to you. Could you comment on this?

**Comment by johtani** [comment]
Hi @GMelo ,

Would be very useful if you could provide some example docs, query, and mappings, in fact a full simple recreation would be awesome.
Can you provide these?

**Comment by GMelo** [comment]
Hello @johtani,
I have written a ugly test to replicate all the behaviours in a single method. 
```java
    @Test
    public void testSimpleSearch() throws ExecutionException, InterruptedException, IOException {
        Client elasticSearchClient = new TransportClient(ImmutableSettings.builder().build())
                .addTransportAddress(new InetSocketTransportAddress("localhost", 9300));

        testObject = jsonBuilder()
                .startObject()
                .field("text")
                .value("輸出貿易 ント")
                .endObject().string();

        if (elasticSearchClient.admin().indices().exists(new IndicesExistsRequest(indexName)).get().isExists())
            elasticSearchClient.admin().indices().prepareDelete(indexName).get();
        try {
            elasticSearchClient.admin().indices().prepareCreate(indexName)
                    .setSettings(ImmutableSettings.settingsBuilder().loadFromSource(jsonBuilder()
                            .startObject()
                            .startObject("analysis")
                                    //
                            .startObject("tokenizer")
                            .startObject("kuromoji_user_dict")
                            .field("type", "kuromoji_tokenizer")
                            .field("mode", "extended")
                            .field("discard_punctuation", "false")
                            .endObject()
                            .endObject()
                                    //
                            .startObject("analyzer")
                            .startObject(JAPANESE_LANGUAGE_ANALYSIS)
                            .field("type", "custom")
                            .field("tokenizer", "kuromoji_user_dict")
                            .endObject()
                            .endObject()
                                    //

                            .endObject()
                            .endObject().string())).get();
        } catch (Exception e) {
            System.out.println("Failed");
        }

        elasticSearchClient.prepareIndex(indexName, indexType).setSource(testObject).get();
        elasticSearchClient.admin().indices().refresh(new RefreshRequest(indexName)).get();

        //matches when a single Kanji is passed
        SearchRequestBuilder searchRequestBuilder = new SearchRequestBuilder(elasticSearchClient);
        BoolQueryBuilder qb = QueryBuilders.boolQuery();
        qb.must(QueryBuilders.queryString("輸")
                .defaultOperator(QueryStringQueryBuilder.Operator.AND)
                .analyzer(ElasticSearchIndexService.JAPANESE_LANGUAGE_ANALYSIS));

        searchRequestBuilder.setQuery(qb);
        SearchResponse singleCharResponse = searchRequestBuilder.setIndices(indexName).execute().actionGet();
        assertEquals(singleCharResponse.getHits().totalHits(), 1);

        //Returns no matches on two Kanji's not separated by space
        searchRequestBuilder = new SearchRequestBuilder(elasticSearchClient);
        qb = QueryBuilders.boolQuery();
        qb.must(QueryBuilders.queryString("輸出")
                .defaultOperator(QueryStringQueryBuilder.Operator.AND)
                .analyzer(ElasticSearchIndexService.JAPANESE_LANGUAGE_ANALYSIS));

        searchRequestBuilder.setQuery(qb);
        SearchResponse twoCharactersNoSpace = searchRequestBuilder.setIndices(indexName).execute().actionGet();
        assertEquals(twoCharactersNoSpace.getHits().totalHits(), 0);

        // Returns one match when separated by a space
        searchRequestBuilder = new SearchRequestBuilder(elasticSearchClient);
        qb = QueryBuilders.boolQuery();
        qb.must(QueryBuilders.queryString("輸 出")
                .defaultOperator(QueryStringQueryBuilder.Operator.AND)
                .analyzer(ElasticSearchIndexService.JAPANESE_LANGUAGE_ANALYSIS));

        searchRequestBuilder.setQuery(qb);
        SearchResponse spaceSeparatedReturn = searchRequestBuilder.setIndices(indexName).execute().actionGet();
        assertEquals(spaceSeparatedReturn.getHits().totalHits(), 1);
        
        //Returns zero on character ン
        searchRequestBuilder = new SearchRequestBuilder(elasticSearchClient);
        qb = QueryBuilders.boolQuery();
        qb.must(QueryBuilders.queryString("ン")
                .defaultOperator(QueryStringQueryBuilder.Operator.AND)
                .analyzer(ElasticSearchIndexService.JAPANESE_LANGUAGE_ANALYSIS));

        searchRequestBuilder.setQuery(qb);
        SearchResponse characterReturned = searchRequestBuilder.setIndices(indexName).execute().actionGet();
        assertEquals(characterReturned.getHits().totalHits(), 0);
    }
```

**Comment by johtani** [comment]
Hi @GMelo 
Thanks for your examples.

I understand you problem, and it is not issue for kuromoji plugin.
You only create the custom analyzer, JAPANESE_LANGUAGE_ANALYSIS, however you didn't tell Elasticsearch where to use it. 
Now you use default analyzer for indexing and JAPANESE_LANGUAGE_ANALYSIS for searching.
You have to use same analyzer for indexing and searching.

In your example, you use "text" field in your document, but Elasticsearch use default analyzer to "text" field. 
You can see your mappings, which you use an analyzer your field , using `curl -XGET http://your_es_host:9200/your_index_name/_mapping`.

You have to call "addMapping()" method and set your custom analyzer to "text" field when you create index.

See : http://www.elastic.co/guide/en/elasticsearch/guide/current/custom-analyzers.html

**Comment by GMelo** [comment]
@johtani,
Thank you, like I said on my first post I was unsure this was a bug and am glad it is not!

However I have been unable to add the mapping, I've added all permutations of adding  addMapping() to the indexName, the indexType with the Json on  http://www.elastic.co/guide/en/elasticsearch/guide/current/custom-analyzers.html but i've had no success, I've also tried adding it in the Fields mapping directly , the same way a non-analized field would be created but with no success. The elasticsearch Java API is very Light, do you know where I can Fiend any examples of adding mappings and adding the analyser to all fields?
either way, Thank you.

**Comment by GMelo** [comment]
I've done some research on google and tried this:
```java
        XContentBuilder xbMapping =
                jsonBuilder()
                        .startObject()
                        .startObject(indexType)
                        .startObject("properties")
                        .startObject("source")
                        .field("type", "string")
                        .endObject()
                        .startObject("text")
                        .field("type", "string")
                        .field("analyzer", JAPANESE_LANGUAGE_ANALYSIS)
                        .endObject()
                        .endObject()
                        .endObject()
                        .endObject();

        elasticSearchClient.admin().indices()
                .preparePutMapping(indexName)
                .setType(indexType)
                .setSource(xbMapping)
                .execute().get();
```

I have also tried:
``` java
            elasticSearchClient.admin().indices().prepareCreate(indexName)
                    .setSettings(ImmutableSettings.settingsBuilder().loadFromSource(jsonBuilder()
                            .startObject()
                            .startObject("analysis")
                                    //
                            .startObject("tokenizer")
                            .startObject("kuromoji_user_dict")
                            .field("type", "kuromoji_tokenizer")
                            .field("mode", "extended")
                            .field("discard_punctuation", "false")
                            .endObject()
                            .endObject()
                                    //
                            .startObject("analyzer")
                            .startObject(JAPANESE_LANGUAGE_ANALYSIS)
                            .field("type", "custom")
                            .field("tokenizer", "kuromoji_user_dict")
                            .endObject()
                            .endObject()
                                    //

                            .endObject()

                            .startObject(indexType)
                            .startObject("properties")
                                    //sort fields
                                    //name
                            .startObject("text")
                            .field("type").value("string")
                            .startObject("fields")
                            .startObject("jap")
                            .field("analyzer").value("japanese_analyzer")
                            .endObject()
                            .endObject()
                            .endObject()
                            .endObject()
                            .endObject()


                            .endObject().string())).get(); 
```
and the results look like this:

curl -XGET http://localhost:9200/test_index/_mapping
{"test_index":{"mappings":{"test_index_type":{"properties":{"source":{"type":"string"},"text":{"type":"string","analyzer":"japanese_analyzer"}}}}}}

but I still get the same behavior...

Thanks again.

**Comment by johtani** [comment]
Great!

If you want to use the analyzer over all fields, you can use "dynamic templates" [1].
And I recommend reading this chapter[2].

Finally, I am closing this ticket, this is not issue.
Please use the [mailing list](https://groups.google.com/forum/?fromgroups#%21forum/elasticsearch) if you have any follow up question.

[1] : 
http://www.elastic.co/guide/en/elasticsearch/guide/current/custom-dynamic-mapping.html#dynamic-templates

[2] : http://www.elastic.co/guide/en/elasticsearch/guide/current/mapping.html
