### ISSUE TITLE
plugin includes too many jars

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch-analysis-kuromoji#61]
Today the assembly is configured as taking transient dependencies of `lucene-analyzers-kuromoji`. But this causes it to bring in more than it should:

    Archive:  elasticsearch-analysis-kuromoji-3.0.0-SNAPSHOT.zip
      Length      Date    Time    Name
    ---------  ---------- -----   ----
      4598170  2015-05-23 08:18   lucene-analyzers-kuromoji-5.2.0-snapshot-1681214.jar
      1555504  2015-05-23 01:20   lucene-analyzers-common-5.2.0-snapshot-1681214.jar
      2335372  2015-05-23 01:20   lucene-core-5.2.0-snapshot-1681214.jar
        20991  2015-05-23 09:09   elasticsearch-analysis-kuromoji-3.0.0-SNAPSHOT.jar
    ---------                     -------
      8510037                     4 files

`lucene-core` and `lucene-analyzers-common` should not be included. They are already in ES-core and at best, including them can only create jar hell.

This is a general problem across many of our plugins, but lets figure out the cleanest way here first.

**Comment by dadoonet** [comment]
Nice finding. Should not be hard to solve and event better we could decide from elasticsearch-plugins pom project to exclude lucene-analyzers-common and other libs already included in elasticsearch core.

I'm not sure (I mean I need to test it) if we can exclude for example `elasticsearch` in the assembly definition file so all elasticsearch and its dependencies will be excluded. May be we have to explicitly exclude all elasticsearch dependency one by one.

**Comment by rmuir** [comment]
Yeah, i dont mind so much if we have to do explicit exclusions, if we can get it inside `plugin/pom.xml` or similar `dev-tools` shared resource folder or whatever we need, so that logic is all in one place.

But we should look into our options to make it easiest to maintain.

**Comment by rmuir** [comment]
Here is a simple proposal @dadoonet 

This would make the file completely generic and usable for all our plugins. The idea is to only use the declared dependencies and not transitive stuff.

So this means for example, the ICU plugin would not just declare `lucene-analyzers-icu` as a dependency, but also `icu4j`. And we would manage the version for `icu4j` in our parent POM to prevent jar hell across different plugins, which I think is needed.

I think its not so bad since plugins dont have many dependencies. (one notable exception: mapper-attachments, but maybe it can just continue to use what it has and we leave it be right now). I think its really important we manage the versions of all our dependencies, not just direct ones. This exact issue has caused ICU conflicts for users before...

    diff --git a/src/main/assemblies/plugin.xml b/src/main/assemblies/plugin.xml
    index 7f051f2..f7fa58a 100644
    --- a/src/main/assemblies/plugin.xml
    +++ b/src/main/assemblies/plugin.xml
    @@ -9,18 +9,10 @@
             <dependencySet>
                 <outputDirectory>/</outputDirectory>
                 <useProjectArtifact>true</useProjectArtifact>
    -            <useTransitiveFiltering>true</useTransitiveFiltering>
    +            <useTransitiveDependencies>false</useTransitiveDependencies>
                 <excludes>
                     <exclude>org.elasticsearch:elasticsearch</exclude>
                 </excludes>
             </dependencySet>
    -        <dependencySet>
    -            <outputDirectory>/</outputDirectory>
    -            <useProjectArtifact>true</useProjectArtifact>
    -            <useTransitiveFiltering>true</useTransitiveFiltering>
    -            <includes>
    -                <include>org.apache.lucene:lucene-analyzers-kuromoji</include>
    -            </includes>
    -        </dependencySet>
         </dependencySets>

**Comment by dadoonet** [comment]
I'm not a big fan of this solution because it means we need to be careful each time a 3rd party lib is updated in our project. So check with `mvn dependency:tree` what is new each we update a lib.
That could lead to a lot of work. IIRC aws for example comes with 4 or 5 other dependencies.

> This exact issue has caused ICU conflicts for users before...
I was not aware of that.

So it's a tradeoff. More complexity and maintenance operation when we upgrade any 3rd party lib vs more safety.
I agree with you that we should be safer first. And also that your solution is definitely shareable across all plugins.

I think it's worth trying it.

We could also mark in the plugin `pom.xml` any lib we know as already in elasticsearch core as `provided`. In that case, I guess that the assembly package won't pull it in the final artifact.

**Comment by rmuir** [comment]
> We could also mark in the plugin pom.xml any lib we know as already in elasticsearch core as provided. In that case, I guess that the assembly package won't pull it in the final artifact.

I looked into this.

This gets pretty messy, because it requires we track all the dependencies of ES and lucene and everything else, its a long list. Much more than say 4 dependencies in the AWS plugin. 

And its hard to think about this logic "backwards". To me its easier to reason about "these are the jars i expect to see in this plugin .zip".

**Comment by dadoonet** [comment]
Ok. It makes sense.

**Comment by dadoonet** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/11647
