### ISSUE TITLE
Tokenization changes when a trailing space is added.

### ISSUE THREAD

**Issue by davidlbowen** [elastic/elasticsearch-analysis-kuromoji#67]
I found a puzzling thing. If you tokenize たてまつ by itself you get a single token たてまつる. However, if you add a trailing space to the string, you get two tokens たてる and まつ. 

Does this make any sense, or is it a bug?

**Comment by gabriel-tessier** [comment]
Hi,
I try to reproduce it on my configuration and I get たてまつ...
Check if you don't have an entry in your synonym or dictionary file.
If you don't have entries in your files can you provide more information about the analyzer you use.

Hope it can help.

**Comment by johtani** [comment]
I reproduce it. And Lucene's Kuromoji is same behavior.

```
curl -XGET "http://localhost:9200/_analyze?analyzer=kuromoji&text=%e3%81%9f%e3%81%a6%e3%81%be%e3%81%a4"
{
   "tokens": [
      {
         "token": "たてまつる",
         "start_offset": 0,
         "end_offset": 4,
         "type": "word",
         "position": 1
      }
   ]
}
```

```
curl -XGET "http://localhost:9200/_analyze?analyzer=kuromoji&text=%e3%81%9f%e3%81%a6%e3%81%be%e3%81%a4%20"

{
   "tokens": [
      {
         "token": "たてる",
         "start_offset": 0,
         "end_offset": 2,
         "type": "word",
         "position": 1
      },
      {
         "token": "まつ",
         "start_offset": 2,
         "end_offset": 4,
         "type": "word",
         "position": 2
      }
   ]
}
```

**Comment by dadoonet** [comment]
As we just expose here a Lucene feature, I'd suggest to open an issue on Lucene side if it makes sense to fix that.

Closing here as I don't think the plugin code itself is buggy here.
